"""create play sessions

Revision ID: 3a1da6d3c91e
Revises: 8c6d4f2a1b30
Create Date: 2026-06-01 23:18:18.853097
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '3a1da6d3c91e'
down_revision: Union[str, None] = '8c6d4f2a1b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('total_cost', sa.Integer(), nullable=False),
    sa.Column('total_slots', sa.Integer(), nullable=False),
    sa.Column('cost_per_slot', sa.Integer(), nullable=False),
    sa.Column('total_charged', sa.Integer(), nullable=False),
    sa.Column('surplus_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by_member_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_play_sessions_created_by_member_id'), 'play_sessions', ['created_by_member_id'], unique=False)
    op.create_table('play_session_participants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('play_session_id', sa.String(length=32), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=False),
    sa.Column('slot_count', sa.Integer(), nullable=False),
    sa.Column('charged_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['play_session_id'], ['play_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_play_session_participants_member_id'), 'play_session_participants', ['member_id'], unique=False)
    op.create_index(op.f('ix_play_session_participants_play_session_id'), 'play_session_participants', ['play_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_play_session_participants_play_session_id'), table_name='play_session_participants')
    op.drop_index(op.f('ix_play_session_participants_member_id'), table_name='play_session_participants')
    op.drop_table('play_session_participants')
    op.drop_index(op.f('ix_play_sessions_created_by_member_id'), table_name='play_sessions')
    op.drop_table('play_sessions')
    # ### end Alembic commands ###
